### ISSUE TITLE
Invalid string length error

### ISSUE THREAD

**Issue by indokathan** [solidusio/solidus_paypal_commerce_platform#135]
Looks like PayPal has max string length validations, and when a product's title is too long, a 422 is returned. 

This happens when clicking one of the PayPal buttons on the cart or product page. 

Here are the console errors: 

![Screen Shot 2021-11-09 at 8 05 17 PM](https://user-images.githubusercontent.com/10875896/141047820-db2916f2-a585-4330-9d9a-84da3a2596fd.png)

and digging a bit deeper, PayPal returns: 

`{"table":{"status_code":422,"error":{"table":{"name":"INVALID_REQUEST","message":"Request is not well-formed, syntactically incorrect, or violates schema.","debug_id":"4365e6b61e3e","details":[{"table":{"field":"/purchase_units/@reference_id=='default'/items/0/name","value":"Guayaki Yerba Mate, Cranberry Pomegranate, Organic Sparkling Alternative to Soda, Tea, and Energy Drinks, 12 Ounce Cans (Pack of 12), 80mg Caffeine","location":"body","issue":"INVALID_STRING_LENGTH","description":"The value of a field is either too short or too long."},"modifiable":true}],"links":[{"table":{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_STRING_LENGTH","rel":"information_link","encType":"application/json"},"modifiable":true}]},"modifiable":true}}}`

In this case, the product's title is: 

Guayaki Yerba Mate, Cranberry Pomegranate, Organic Sparkling Alternative to Soda, Tea, and Energy Drinks, 12 Ounce Cans (Pack of 12), 80mg Caffeine

**Comment by DanielePalombo** [comment]
@indokathan Can you take a look at the related PR and check if it fix your issue?
