### ISSUE TITLE
Gem does not support Ruby 3.0

### ISSUE THREAD

**Issue by RyanofWoods** [solidusio/solidus_paypal_commerce_platform#145]
### General information:
This gem has a dependency of [paypal-checkout-sdk](https://github.com/paypal/Checkout-Ruby-SDK) which has a dependency of [paypal-http](https://github.com/paypal/paypalhttp_ruby), both of these gems do not support Ruby 3.0 yet. This is causes issues as seen here: https://github.com/solidusio-contrib/solidus_paypal_commerce_platform/issues/132

### Example:
The above issue highlights that the incompatiblity causes issues with our [execute method](https://github.com/paypal/paypalhttp_ruby/blob/b444edf8e55ddf7e4bb5ab967cdd8ad9c9c9ec29/lib/paypalhttp/serializers/form_encoded.rb#L8), which is a core method in the gem. This trickles down to `URI.escape` method [used in paypal-http]().

This has been "deprecated" for [10 years](https://github.com/ruby/ruby/commit/869e2dd8c8efc1e7a043c9eee82d97c47befbcc7) and removed in [Ruby 3.0](https://github.com/ruby/ruby/commit/abbd3241522495e8d8634c0c01a42453f76ce6b8#diff-936b286152b1184cde04f027289d65e633d0f3ee52fdc42cf4eb072c24312e15)

`paypal-http` has an issue for the Ruby 3.0 incompatibility : https://github.com/paypal/paypalhttp_ruby/issues/12

The mentioned dependencies might not be the only dependencies that does not support Ruby 3.0, so this should be investigated further.

### Proposed solution:
As soon as the PayPal dependencies are compatible with Ruby 3.0 we should attempt to make the gem compatible with it as well.

### Temporary solution:
The `required_ruby_version` in the `gemspec`  has been rollbacked to pre 3.0 to prevent developers having the same issue.

**Comment by xeruf** [comment]
Why is this not fixed after almost a year, and why does bundler not recognize the conflict for me? My `Gemfile` states:
```
ruby '>= 3.0'
gem 'solidus_paypal_commerce_platform'
```
And it installs without complaint... What do I do now, I want to start using the store in a few days?

**Comment by xeruf** [comment]
apparently the upstream issue is fixed, so maybe this can be resolved by updating dependencies?

**Comment by RyanofWoods** [comment]
Can this be closed now @cpfergus1 and @elia?
https://github.com/solidusio/solidus_paypal_commerce_platform/pull/161

**Comment by elia** [comment]
@RyanofWoods for sure, master is testing against ruby 2.7, 3.0, and 3.1 👍👍👍
