### ISSUE TITLE
Release 0.6 and attach that version to a different branch

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus_paypal_commerce_platform#169]
We need to start working on the version that will be compatible with the new starter frontend. The current version is compatible with the legacy frontend and will live on a `0.x` branch on the repo.

**Comment by elia** [comment]
✅ Done https://github.com/solidusio/solidus_paypal_commerce_platform/releases/tag/v0.6.0
https://rubygems.org/gems/solidus_paypal_commerce_platform/versions/0.6.0
