### ISSUE TITLE
Decide about the testing approach for extensions that involve SSF code

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus_paypal_commerce_platform#171]
_Originally posted by @waiting-for-dev in https://github.com/solidusio/solidus_paypal_commerce_platform/pull/166#discussion_r1032533834_
      

We need to decide which one of these options we do prefer:

1. Create a special, isolated dummy app and copy all the specs over, then run all the specs from that dummy app.
2. Do the above, but only for code that involves the storefront. All the rest of the specs (models, services, backend, API) will be tested in the extension engine, as we are doing in any other extension, and as we are used to do following the "Rails way".

**Comment by elia** [comment]
After discussing this live we concluded that for now we're still spiking the solution and will keep things as they are for now. 

We might revise the situation down the road, once we applied the same technique to other extensions, and before building tooling (e.g. in solidus_dev_support). 

At that point we'll have more data points, making it a more informed decision, not excluding entirely different approaches that might emerge by then.

_cc @waiting-for-dev @chrean @aldesantis for additional details and considerations that I might have missed from the conversation we had_
