### ISSUE TITLE
Solidus 3.2 doesn't install SPCP's checkout page when PayPal is chosen as the payment method

### ISSUE THREAD

**Issue by gsmendoza** [solidusio/solidus_paypal_commerce_platform#172]
## Solidus Version

Solidus 3.2

## Expected behavior

Given I have installed Solidus 3.2 on my Rails app
And I have chosen PayPal as the payment method
And I have setup PayPal Commerce Platform via the Payment Methods Admin page
When I check out an item
Then I should see PayPal as a payment method in the checkout payment page

## Current behavior

I get the following error in `/checkout/payment`

```
ActionView::MissingTemplate in Checkouts#edit
Showing /home/gsmendoza/repos/gsmendoza/solidus_store/app/views/checkouts/steps/payment_step/_payment_method_controls.html.erb where line #4 raised:

Missing partial checkouts/payment/_paypal_commerce_platform with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}.
```

## Screenshots

![image](https://user-images.githubusercontent.com/61476/206343342-8bc09082-dede-4d4c-9c25-9621342cc683.png)

## Test app

See the Rails app in https://github.com/gsmendoza/solidus_store/tree/rails-7-0-4--solidus-3-2-4--solidus-paypal-commerce-platform, which installed SolidusPaypalCommercePlatform during the Solidus installation.

## Background

Was originally reported in the Solidus Slack Channel: https://solidusio.slack.com/archives/C0JBKDF35/p1670354516954979.

**Comment by elia** [comment]
I gather from the screenshot that this issue arose while using v0.6 and the solidus_starter_frontend. This is not supported, you should either use [v1.0.0.beta1](https://rubygems.org/gems/solidus_paypal_commerce_platform/versions/1.0.0.beta1) or the [classic frontend](https://rubygems.org/gems/solidus_frontend).

**Comment by gsmendoza** [comment]
@elia Sorry for the confusing screenshot. I probably saved the screenshot before testing it on 1.0.0.beta1.
