### ISSUE TITLE
wizard doesn't create payment method in v1.0.0.beta1 and no partial.

### ISSUE THREAD

**Issue by czepesch** [solidusio/solidus_paypal_commerce_platform#174]
In Wizard, after step "Agree and Connect" nothing happens, method is not created.

**Solidus Version**:
3.2.4

**To Reproduce**
create new rails app, install latest Solidus, install **solidus_paypal_commerce_platform** gem of version v1.0.0.beta1.
Use Wizard at admin/payment_methods.

**Screenshots**
![image](https://user-images.githubusercontent.com/54212560/206914488-ac86a060-af33-4cb5-bd41-879ddd2b0846.png)

**Spree.rb**
```
  Rails.application.config.to_prepare do
    Spree::Config.static_model_preferences.add(
      SolidusPaypalCommercePlatform::PaymentMethod,
      'paypal_commerce_platform_credentials', {
        test_mode: !Rails.env.production?,
        client_id: Rails.application.credentials.paypal.client_id,
        client_secret: Rails.application.credentials.paypal.client_secret,
        display_on_product_page: true,
        display_on_cart: true,
      }
    )
  end
```

**Desktop :**
 - Ubuntu 20.04
 - Latest Chrome and Edge

**Comment by elia** [comment]
Thanks for the detailed report! 🙌 

🤔 this is tested and designed to work with the master version of solidus_starter_frontend (which is tied to the upcoming solidus 3.3). 

I can think of two potential solutions that I can suggest:
- you can diff the updated templates from SSF with your installation and see if there's any change that can fix this error
- you can try opening a PR to make it work with solidus 3.2 which I'd be happy to review and do what I can to bring it to the finish line and merge it

I'm gonna close this as not planned, but happy to reopen if you wanna take up the challenge 💪

**Comment by gsmendoza** [comment]
@elia This seems to be the same issue as https://github.com/solidusio/solidus_paypal_commerce_platform/pull/173. I have a pending PR to fix the issue. Please see https://github.com/solidusio/solidus_paypal_commerce_platform/pull/173. Have you looked into it?

**Comment by elia** [comment]
@gsmendoza thanks for the call out, I merged that PR, and I'll probably release another beta with that fix soon, @czepesch you mind trying again with the new beta once it's out?

**Comment by czepesch** [comment]
@elia sure

**Comment by elia** [comment]
@czepesch beta2 is out! https://github.com/solidusio/solidus_paypal_commerce_platform/releases/tag/v1.0.0.beta2

**Comment by czepesch** [comment]
@elia It's definitely better now, I was able to create payment method with wizard.
Partial also in place.

But I can't perform test payment with credit card or paypal account balance.
On credit card there is: "Things don't appear to be working at the moment."
On account balance: 
```
[SolidusPaypalCommercePlatform::Client#execute] #<PayPalCheckoutSdk::Orders::OrdersAuthorizeRequest:0x00007f5575abe8a8 @headers={"Content-Type"=>"application/json"}, 
@body=nil, @verb="POST", @path="/v2/checkout/orders/4E273902K31525213/authorize?">
[SolidusPaypalCommercePlatform::Client#execute] #<OpenStruct name="UNPROCESSABLE_ENTITY", details=[#<OpenStruct issue="TRANSACTION_REFUSED", description="The request was refused">], 
message="The requested action could not be performed, semantically incorrect, or failed business validation.",
 debug_id="93f509a199c21", links=[#<OpenStruct href="https://developer.paypal.com/docs/api/orders/v2/#error-TRANSACTION_REFUSED", rel="information_link", method="GET">]>
```

Maybe I'm doing something wrong, will try again..

**Comment by elia** [comment]
PayPal is incredibly cryptic with its error messages. Last time I faced a similar message it was an issue with how amount numbers were formatted, but no docs anywhere about it, and we solved it by (painful) trial and error. The only thing we could rely upon is examples in the docs, and trying to adhere as much as possible to them. That's all I have, but if there's anything else I can do just let me know 🙋‍♂️

**Comment by czepesch** [comment]
I manually put API credentials from sandbox business account (thx George) and it works now.
The problem with Wizard is that API credentials it creates - nowhere to be found in Paypals sandbox web interface, I couldn't (are they correct at all?)

**Comment by czepesch** [comment]
@elia @gsmendoza 
It happens when I want to remove credentials from method properties and replace it with ENVs.
I choose **Preference Source** - _paypal_commerce_platform_credentials_
And my **spree.rb** contents this:
```
  Rails.application.config.to_prepare do
    Spree::Config.static_model_preferences.add(
      SolidusPaypalCommercePlatform::PaymentMethod,
      'paypal_commerce_platform_credentials', {
        test_mode: !Rails.env.production?,
        client_id: Rails.application.credentials.paypal.client_id,
        client_secret: Rails.application.credentials.paypal.client_secret,
        display_on_product_page: true,
        display_on_cart: true,
      }
    )
  end
```
This deserves to be separate issue or I'm missing something? Because I see that source code of beta2 has this golden_button_message line in locale file.

![image](https://user-images.githubusercontent.com/54212560/207397214-2ccf7293-cafc-4463-8f73-8774a4c0a866.png)

**Comment by gsmendoza** [comment]
@czepesch Please see PRs #177 and #179. Thanks!
