### ISSUE TITLE
Dummy app not compatible with main search autocomplete?

### ISSUE THREAD

**Issue by gsmendoza** [solidusio/solidus_paypal_commerce_platform#188]
## Solidus Version

3.4.0.dev

## To Reproduce

Run `bin/rails-dummy-app`, then run `bin/rspec spec/system/search_spec.rb`. Specs should fail:

```
7 examples, 7 failures

Failed examples:

rspec ./spec/system/search_spec.rb:12 # searching products falls back to normal search for plain HTML requests
rspec ./spec/system/search_spec.rb:60 # searching products with JS enabled closes autocomplete suggestions clicking outside the search input
rspec ./spec/system/search_spec.rb:42 # searching products with JS enabled clicks on a suggestion pressing enter
rspec ./spec/system/search_spec.rb:30 # searching products with JS enabled scrolls up and down through suggestions using up/down arrow keys
rspec ./spec/system/search_spec.rb:20 # searching products with JS enabled shows autocomplete suggestions
rspec ./spec/system/search_spec.rb:51 # searching products with JS enabled closes autocomplete suggestions pressing esc key
rspec ./spec/system/search_spec.rb:25 # searching products with JS enabled automatically selects the first suggestion
```

To test in development,

1. Create the dummy app like above, then run `bin/rails-dummy-app db:seed` and `bin/rails-dummy-app spree_sample:load` to seed your development database.
2. Run `bin/rails-dummy-app server` to run the server,
3. In `https://localhost:3000`, try to search for a product. You should see no response:

![image](https://user-images.githubusercontent.com/61476/217733822-9f0f4602-ce1e-4f5a-9c5e-fcc84fd9a4f5.png)

4. If you enter the search term, you'd see the following error:

![image](https://user-images.githubusercontent.com/61476/217733919-a27f6fb7-3c91-400f-952b-cf763b76ca76.png)

## Additional context

The new autocomplete search was introduced in https://github.com/solidusio/solidus_starter_frontend/pull/300.

I'm seeing the same issue on my ongoing work with SolidusBraintree (See https://github.com/solidusio/solidus_braintree/issues/91 and https://github.com/solidusio/solidus_braintree/tree/gsmendoza/91-ssf-dummy-app).

However, on a regular Solidus app, the search autocomplete seems to work fine with SolidusPaypalCommercePlatform. See https://github.com/gsmendoza/solidus_store/tree/rails-7-0-4--solidus-3-4-0-dev--spcp:

![image](https://user-images.githubusercontent.com/61476/217737062-48bd4dd0-d50e-4efe-b182-a3a9918489ef.png)

**Comment by gsmendoza** [comment]
@kennyadsl @elia I tried removing `--skip-javascript` from the sandbox and dummy-app scripts. This seems to have fixed the autocomplete in the Rails dummy app, but I'm still encountering the following issues:

1. `bin/rspec spec/system/search_spec.rb` is still failing.
2. I'm getting the following errors when I try the search autocomplete feature on the sandbox app: 
![image](https://user-images.githubusercontent.com/61476/217749736-4f65342d-fc93-4d04-a23b-4a202b881b11.png)

I'll continue investigating these issues tomorrow, but if you can look into them, I would appreciate it!

**Comment by kennyadsl** [comment]
I think I identified the issue: dummy and sandbox rails apps are generated with `--skip-bundle` option, which [skips the importmap, turbo and stimulus installation](https://github.com/rails/rails/blob/9fcfbe5306cf632f5f47fa8bb5dfa36545ab1be6/railties/lib/rails/generators/app_base.rb#L448-L461). At that point they are added to the app Gemfile, but they are not installed. Trying to remove the `--skip-bundle` option.

**Comment by kennyadsl** [comment]
#189 should fix it!
